title: Shawn Bernard
logo: headshot.jpg
description: "Hello! I'm Shawn, a 24-year-old data enthusiast based in Brooklyn, NY. Despite my initial goals for medical school, introductory data science courses in college sparked a new passion within me. Diving into the world of data science, I pursued a Master's to refine my skills and knowledge. Now, I've begun an exciting career as a data scientist, eager to uncover insights that drive change. Beyond data, I enjoy spending time with loved ones, exploring new places, playing basketball, and hiking." 
show_downloads: False
theme: jekyll-theme-minimal
