title: Shawn Bernard
logo: headshot.png
#description: 
show_downloads: False
theme: jekyll-theme-minimal
author:
  name: Your Name
  bio: Web Developer
  location: City, Country
  email: your.email@example.com
  twitter_username: your_twitter_handle
  github_username: your_github_username
